name: Deploy to GitHub Pages

on:
  push:
    branches: 'main'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
          BASE_PATH: '/projects/sveltekit-static'
        run: |
          npm run build
          
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: giancohs/giancohs.github.io
          token: ${{ secrets.PERSONAL_TOKEN }} # in the settings of the target repository, go to secrets and add PERSONAL_TOKEN from the general settings of the github account
          path: public-page

      - name: Copy build to target repo
        run: |
          rm -rf public-page/projects/sveltekit-static
          mkdir -p public-page/projects/sveltekit-static
          cp -r build/* public-page/projects/sveltekit-static/
          
      - name: Commit and push changes
        run: |
          cd public-page
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add projects
          git commit -m "Update projects/sveltekit-static from private repo"
          git push